config/routes.rb
Rayons::Application.routes.draw do
  devise_for :users

  devise_scope :user do
    get "login", to: "devise/sessions#new"
    get "logout", to: "devise/sessions#destroy"
  end

  namespace :api do
    resources :items, only: [:show] do
      collection do
        get "daily"
        get "random"
      end
    end
  end

  resources :items, except: [:new] do
    collection do
      get "discover"
      get "import"
      post "import"
      get "random"
      get "latest"
      get "/page/:page", action: :index

      resource :alexa, only: [], controller: "items/alexa" do
        post "random"
      end
    end

    member do
      post "mark_as_cleaned"
    end
  end

  resources :stats, only: [:index] do
    collection do
      get "counts_by_day"
      get "time_machine"
      get "words_for_field"
    end
  end

  resources :tracks, only: [:index, :show] do
    collection do
      get "find"
    end
  end

  get "/stats/time_machine/:month/:day", to: "stats#time_machine"
  get "/mu-9306e982-5e21cfff-5e7a9bbe-e08bb3ce", to: "application#blitz"
  get "/opensearch.xml", to: "application#opensearch"
  get "/status", to: "application#status"

  authenticate :user do
    root to: "items#index", as: :authenticated_root
  end
  root to: redirect("/users/sign_in")
end

app/models/track.rb
class Track < ApplicationRecord
  belongs_to :item

  validates_presence_of :artist, :item_id, :name

  default_scope { where(deleted: false) }

  def possible_covers
    self.class.where("name = ? AND artist != ?", name, artist)
  end

  def possible_alternates
    self.class.where("name = ? AND artist = ? AND id != ?", name, artist, id)
  end

  def destroy
    self.deleted = true
    save!
  end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController

  before_action :authenticate_user!
  include Pagy::Backend

  def index
    @track_finder = TrackFinder.new(track_finder_params)
    @artists = [nil] + Track.order(:artist).distinct.pluck(:artist)
    @pagy, @tracks = pagy(@track_finder.tracks)
  end

  def show
    @track = Track.find(params[:id])
  end

  private

  def track_finder_params
    params.permit(:name, :artist)
  end
end

app/views/tracks/index.html.haml
.container-fluid
  %h1
    Tracks
    - if params[:name].present?
      with name "#{params[:name]}"
    - if params[:artist].present?
      by "#{params[:artist]}"
    (#{number_with_delimiter(@track_finder.count)})

  = form_with(url: tracks_path, method: "GET") do |f|
    .form-group
      = f.label :name
      = f.text_field :name, value: params[:name]

    .form-group
      = f.label :artist
      = f.select :artist, @artists, selected: params[:artist]

    .form-group
      %button.btn.btn-primary.btn-large{ type: "submit" } Find tracks

  %table.table
    %thead
      %tr
        %th{ scope: "col" } Artist
        %th{ scope: "col" } Name
        %th{ scope: "col" } Duration
        %th{ scope: "col" } Item
        %th{ scope: "col" } Number
        %th{ scope: "col" } Info
    %tbody
      - @tracks.each do |track|
        %tr
          %td= track.artist
          %td= track.name
          %td= track.duration
          %td
            %a{ href: item_path(track.item) }= track.item.title
          %td= track.number
          %td
            %a{ href: track_path(track) } link

  != pagy_bootstrap_nav(@pagy)

app/views/tracks/show.html.haml
.container-fluid
  %h1 "#{@track.name}" by #{@track.artist}

  .row
    .col-md-7
      %p
        %strong Duration:
        = @track.duration
      %p
        %strong Item:
        %a{ href: item_path(@track.item) }= @track.item.title
      %p
        %strong Number:
        = @track.number
      
      %h2 Possible Covers:
      - if @track.possible_covers.exists?
        %ul
          - @track.possible_covers.each do |track|
            %li
              %a{ href: track_path(track) } "#{track.name}" by #{track.artist} on #{track.item.title}
      - else
        None
      %h2  Possible Alternate Versions:
      - if @track.possible_alternates.exists?
        %ul
          - @track.possible_alternates.each do |track|
            %li
              %a{ href: track_path(track) } "#{track.name}" by #{track.artist} on #{track.item.title}
      - else
        None
      