config/routes.rb
Rayons::Application.routes.draw do
  devise_for :users

  devise_scope :user do
    get "login", to: "devise/sessions#new"
    get "logout", to: "devise/sessions#destroy"
  end

  namespace :api do
    resources :items, only: [:show] do
      collection do
        get "daily"
        get "random"
      end
    end
  end

  resources :items, except: [:new] do
    collection do
      get "discover"
      get "import"
      post "import"
      get "random"
      get "latest"
      get "/page/:page", action: :index

      resource :alexa, only: [], controller: "items/alexa" do
        post "random"
      end
    end

    member do
      post "mark_as_cleaned"
    end
  end

  resources :stats, only: [:index] do
    collection do
      get "counts_by_day"
      get "time_machine"
      get "words_for_field"
    end
  end

  resources :tracks, only: [:index, :show] do
    collection do
      get "find"
    end
  end

  get "/stats/time_machine/:month/:day", to: "stats#time_machine"
  get "/mu-9306e982-5e21cfff-5e7a9bbe-e08bb3ce", to: "application#blitz"
  get "/opensearch.xml", to: "application#opensearch"
  get "/status", to: "application#status"

  authenticate :user do
    root to: "items#index", as: :authenticated_root
  end
  root to: redirect("/users/sign_in")
end

app/models/item.rb
class Item < ActiveRecord::Base
  before_validation :blank_discogs
  after_save :update_item_counts

  validates_presence_of :price_paid
  validates_format_of :discogs_url, with: URI.regexp(%w(http https)), allow_nil: true

  has_many :tracks
  has_neighbors :embedding, normalize: true, dimensions: 1536

  scope :added_on_day, ->(date) { where ["created_at >= ? AND created_at <= ?", date.to_date, (date + 1.day).to_date] }

  default_scope { where(deleted: false) }

  SORT_ORDER = %w(artist title year label format).freeze

  def self.search(query = "")
    query = query.to_s
    if !query.present?
      all
    elsif query == query.to_i.to_s
      ids = Item.basic_search(query).map(&:id)
      where(["year = ? OR id IN (?)", query, ids])
    else
      basic_search(query)
    end
  end

  def self.advanced_search(query = {})
    if !query.present?
      all
    else
      query = query.select { |_term, value| value.present? }
      if (years = query.delete("years"))
        if query.present?
          ids = Item.basic_search(query).map(&:id)
          where(["id IN (?) AND year BETWEEN ? AND ?", ids, years["minimum"], years["maximum"]])
        else
          where(["year BETWEEN ? AND ?", years["minimum"], years["maximum"]])
        end
      else
        basic_search(query)
      end
    end
  end

  def self.sorted(first = SORT_ORDER[0], direction = "ASC")
    first ||= SORT_ORDER[0]
    direction ||= "ASC"

    first = "to_number(price_paid, '9999999.99')" if first == "price_paid"
    sort_order = [first] + (SORT_ORDER - [first])
    sort_order = sort_order.map { |s| "#{s} #{direction}" }

    order( Arel.sql(sort_order.join(",")))
  end

  # Generate CSV of items and yield each row to a block
  def self.to_csv
    headers = Item.column_names - %w(id deleted)
    csv = ""

    csv << CSV::Row.new(headers, headers, true).to_s
    yield csv if block_given?

    Item.find_each(batch_size: 50) do |item|
      values = item.attributes.values_at(*headers)
      row = CSV::Row.new(headers, values, false).to_s
      yield row if block_given?
      csv << row
    end
    csv
  end

  # Import a csv file object and create an Item object for each row
  #
  # @param [File] file The csv file to be read
  # @return [Array] The array of items created
  def self.import_csv_file(file)
    raise "You must include a file" unless file

    # construct an array of hashes from the data
    # from http://snippets.dzone.com/posts/show/3899
    csv_data = CSV.read(file.tempfile)
    headers = csv_data.shift.map(&:to_s)
    string_data = csv_data.map { |row| row.map { |cell| cell.to_s.force_encoding("utf-8") } }
    array_of_hashes = string_data.map { |row| Hash[*headers.zip(row).flatten] }

    items = []

    Item.transaction do
      array_of_hashes.each { |attrs| items << Item.create(attrs) }
    end

    items
  end

  def self.random
    offset(rand(count)).first
  end

  # def self.all_genres and def self.all_styles
  # Use metaprogramming here to prevent sql injection if the field were a method parameter
  class << self
    %w[genre style].each do |field|
      define_method :"all_#{field.pluralize}" do
        sql = <<-SQL
          select
            distinct unnest(#{field.pluralize}) as #{field}
           from items
           order by #{field}
        SQL
        ActiveRecord::Base.connection.exec_query(sql).rows.flatten
      end
    end
  end

  def added_on
    created_at.strftime("%m.%d.%y")
  end

  def as_json(options = {})
    super(options.merge(methods: :added_on))
  end

  def as_embedding
    str = <<~EOF
      Title: #{title}
      Artist: #{artist}
      Label: #{label}
      Format: #{format}
      Added to collection: #{created_at.strftime("%c")}
    EOF

    if genres.present?
      str << "Genres: #{genres.join(", ")}\n"
    end

    if styles.present?
      str << "Styles: #{styles.join(", ")}\n"
    end

    if notes.present?
      str << notes
    end

    str.strip
  end

  def similar_items
    nearest_neighbors(:embedding, distance: "cosine").limit(10)
  end

  def destroy
    self.deleted = true
    save!
    tracks.destroy_all
  end

  private

  def blank_discogs
    self.discogs_url = nil if discogs_url.blank?
  end

  def update_item_counts
    ItemCount.update_or_create_day created_at.to_date
  end
end

app/controllers/api/items_controller.rb
module Api
  class ItemsController < BaseController
    def daily
      @item = ItemOfTheDay.new

      render json: @item
    end

    def random
      @item = Item.random

      render json: ItemBlueprint.render(@item)
    end

    def show
      @item = Item.find(params[:id])

      render json: ItemBlueprint.render(@item)
    end
  end
end

app/controllers/items/alexa_controller.rb
class Items::AlexaController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :verify_alexa

  def random
    presenter = ItemAlexaPresenter.new(params)

    render json: presenter
  end

  private

  def verify_alexa
    unless AlexaVerifier.valid?(request)
      render body: nil, status: :bad_request
    end
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  include ApplicationHelper
  include ActionController::Live

  before_action :authenticate_user!
  before_action :edit_discogs_param, only: [:index, :create, :update]

  # GET /
  # GET /items
  # GET /items.json
  # GET /items.csv
  def index
    respond_to do |format|
      format.html do
        @presenter = index_presenter
      end
      format.json { render json: index_presenter.as_json }
      format.csv { index_csv }
    end
  end

  # GET /items/discover
  def discover
    base_cache_key = ["discover", Item.unscoped.maximum(:updated_at).to_i].join("/")
    @genres = Rails.cache.fetch("#{base_cache_key}/genres") { [nil] + Item.all_genres }
    @styles = Rails.cache.fetch("#{base_cache_key}/styles") { [nil] + Item.all_styles }
    @formats = [nil] + ItemSearchPresenter.new.formats

    if params[:q]
      @item = ItemDiscoverPresenter.new(params[:q]).item

      if @item
        redirect_to @item, only_path: true
      else
        flash.now[:error] = "No item found. Try again!"
      end
    end
  end

  # GET /items/latest.json
  def latest
    number_of_items = params[:num].to_i
    number_of_items = 5 if number_of_items.zero?
    @items = Item.order("created_at DESC").limit(number_of_items)
    render json: @items
  end

  # GET /items/1
  def show
    @item = Item.find(params[:id])

    render html: (cache [@item, "3"] do
      @release = DiscogsRelease.new(@item)
      render_to_string
    end)
  end

  # GET /items/1/edit
  def edit
    @item = Item.find(params[:id])
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: "Item was successfully created." }
        format.json { render json: @item, status: :created, location: @item }
      else
        default_error_response(format, "new", @item)
      end
    end
  end

  # PUT /items/1
  def update
    @item = Item.find(params[:id])
    params[:item] = params[:item].reject { |k, _| !Item.column_names.include?(k) }

    respond_to do |format|
      if @item.update(item_params)
        redirect_to @item, notice: "Item was successfully updated."
      else
        default_error_response(format, "edit", @item)
      end
    end
  end

  def mark_as_cleaned
    @item = Item.find(params[:id])

    respond_to do |format|
      if @item.update(last_cleaned_at: Time.now)
        redirect_to @item, notice: "Item was successfully updated."
      else
        default_error_response(format, "edit", @item)
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item = Item.find(params[:id])
    @item.destroy

    respond_to do |format|
      format.html { redirect_to items_url }
      format.json { head :no_content }
    end
  end

  # GET /items/import
  # POST /items/import
  def import
    if request.post?
      @items, @errors = ItemImporter.new(params[:urls].split, params[:notes]).import
    end
  end

  # GET /items/random
  def random
    @item = Item.random

    redirect_to @item
  end

  private

  def edit_discogs_param
    params[:sort] = "discogs_url" if params[:sort] == "discogs"
    if params[:item]
      params[:item][:discogs_url] ||= params[:item][:discogs]
    end
  end

  def index_presenter
    ItemJsonPresenter.new(params.slice(:sort, :direction, :search, :page))
  end


  def item_params
    params.require(:item).permit(:artist, :condition, :format, :label, :price_paid, :title, :year, :color, :notes, :discogs_url, :last_cleaned_at, genres: [], styles: [])
  end

  def index_csv
    set_streaming_headers
    headers.merge!("Content-Type" => "text/csv",
                   "Content-disposition" => "attachment; filename=\"rayons_#{Time.now.to_i}.csv\"")
    Item.to_csv { |row| response.stream.write row }
    response.stream.close
  end
end

app/helpers/items_helper.rb
module ItemsHelper
  def discogs_percent
    number_with_url = Item.where("discogs_url IS NOT NULL").count
    "#{number_with_delimiter(number_with_url)} / #{number_with_delimiter(Item.count)}"
  end

  def column_charts_options
    {
      backgroundColor: "white",
      colors: ["#FBBE1E"],
    }
  end

  def pie_charts_options
    {
      backgroundColor: {
        fill: "white",
        stroke: "white",
      },
      pieSliceBorderColor: "#222",
      pieSliceText: "label",
      pieSliceTextStyle: { color: "black", fontSize: "12" },
      legend: { position: "none" },
    }
  end

  def items_per_month
    Item.group_by_month(:created_at, format: "%b %Y").count
  end

  def items_per_day_of_week
    days_of_week = %w(Sunday Monday Tuesday Wednesday Thursday Friday Saturday)
    result = {}
    Item.group_by_day_of_week(:created_at).count.map do |k, v|
      result[days_of_week[k.to_i]] = v
    end
    result
  end

  def random_discogsless_url
    item_url(Item.where("discogs_url IS NULL").sample)
  end

  def top_10(field)
    @total_count ||= Item.count
    stats = @item_stats || ItemStats.new
    stats.top_10(field).map do |value, count|
      percentage = count * 100.0 / @total_count
      "<p><strong>#{value}</strong>: #{number_with_delimiter(count)}: <em>#{percentage.round(2)}%</em></p>"
    end.join.html_safe
  end

  def field_headers
    ["Title", "Artist", "Year", "Label", "Format", "Condition", "Color", "Price Paid", "Notes"]
  end
end

app/views/items/_form.html.haml
= form_for item, html: { class: "item-form" } do |f|
  - if item.errors.any?
    #error_explanation
      %h2= "#{pluralize(item.errors.count, "error")} prohibited this item from being saved:"
      %ul
        - item.errors.full_messages.each do |msg|
          %li= msg

  - (Item.column_names - %w[id created_at updated_at deleted genres styles embedding embedding_md5 last_cleaned_at]).each do |field|
    .form-group
      = f.label field
      = f.text_field field, class: "form-control"
  - %w[genres styles].each do |field|
    .form-group
      = f.label field
      - item.send(field).to_a.each do |v|
        = f.text_field field, value: v, name: "item[#{field}][]", class: "form-control"
  .form-group
    %button.btn.btn-primary{ type: "submit" } Save

app/views/items/_item.html.haml
%tr{"data-id" => "#{item.id}"}
  %td.item-title
    %a{:href => "/items/#{item.id}"}= item.title
  %td.item-artist #{item.artist}
  %td.item-year #{item.year}
  %td.item-label #{item.label}
  %td.item-format #{item.format}
  %td.item-condition #{item.condition}
  %td.item-color #{item.color}
  %td.item-price_paid #{item.price_paid}
  %td.item-notes #{item.notes}
  %td.item-added_on #{item.added_on}
  %td.item-edit
    %a.item-edit{:href => "/items/#{item.id}/edit"}
      %i.glyphicon.glyphicon-pencil
  %td.item-delete
    %a.item-delete{:href => "/items/#{item.id}"}
      %i.glyphicon.glyphicon-trash

app/views/items/_lists.html.haml
- lists = @item.playlists

- if lists.present?
  %p
    %b Playlists
    %br
    %ul
      - lists.each do |list|
        %li
          %a{ href: playlist_path(list) }= list.name
      - if local_assigns[:editable]
        %li
          %form{ action: playlists_path, method: 'POST' }
            %input{ type: 'text', placeholder: 'Add To Playlist', name: 'playlist[name]' }
            %input{ type: 'hidden', name: 'item_id', value: @item.id }
  

app/views/items/discover.html.haml
.container-fluid

  - if flash[:error]
    .message.error.text-center= flash[:error]

  %h1 Discover

  = form_for(:q, url: "/items/discover", method: "GET") do |f|
    .form-group
      = f.label :genre
      = f.select :genre, @genres

    .form-group
      = f.label :style
      = f.select :style, @styles

    .form-group
      = f.label :format
      = f.select :format, @formats

    .form-group
      %button.btn.btn-primary.btn-large{ type: "submit" } Discover something good

app/views/items/edit.html.haml
.container-fluid
  %h1 Edit

  = render 'form', item: @item

  .row
    .col-md-12
      = link_to 'Show', @item
      \|
      = link_to 'Back', :back

app/views/items/import.html.haml
.container-fluid#importer
  %h1 Import items from Discogs

  - if @errors
    - @errors.each do |error|
      .message.error.text-center= error

  = form_with url: import_items_path, method: :post do |form|
    .form-group
      = form.label "Discogs URLs (one per line)"
      = form.text_area :urls, rows: 3, value: params[:urls], class: "form-control"
    .form-group
      = form.label "Notes", for: :notes
      = form.text_field :notes, value: params[:notes], class: "form-control"
    .form-group
      %button.btn.btn-primary{ type: "submit" } Import

  - if @items
    - @items.each do |item|
      .card
        .card-header
          %h2.mb-0
            %a{ href: item_path(item) } #{item.artist} - #{item.title}
        .card-body
          = render "form", item: item

app/views/items/index.html.haml
.container-fluid#items
  #add-new.text-center
    %form.form-inline.ajax{ :action => '/items', :method => 'post' }
      .form-group
        = token_tag(nil)
        - field_headers.each do |field|
          %input.form-control{ :type => 'text', :name => "item[#{field.parameterize(separator: "_")}]", :placeholder => field }
        %input.form-control{ :type => 'text', :name => "item[discogs_url]", :placeholder => "Discogs URL" }
        %button.btn.btn-primary{ :type => 'submit' } Add

  .table-responsive
    %table.table{ 'data-sort' => params[:sort], 'data-direction' => params[:direction] }
      %thead
        %tr
          - field_headers.each do |field|
            %th{ :class => "item-#{field.parameterize(separator: "_")}" }
              - sort = field.parameterize(separator: "_")
              %a{ :href => '', 'data-sort' => sort }
                - if field == "Price Paid"
                  Paid
                - else
                  = field
          %th
            %a.added_on{ :href => '', 'data-sort' => 'created_at'}
              Added
          %th
          %th
      %tbody
        - cache("#{@presenter.cache_key}/html") do
          = render @presenter.items
  .text-center!= pagy_bootstrap_nav @presenter.pagination

:javascript
  window.filter_options = #{params.slice(:sort, :direction, :search, :q, :page).to_json.html_safe};

- content_for :nav do
  %ul.nav.navbar-nav
    %li
      %a!= pagy_info @presenter.pagination
    %li
      %a{ :href => '/stats' } stats
    %li
      %a{ :href => random_items_path } random
    %li
      %a{ href: discover_items_path } discover
    %li
      %a{ href: tracks_path } tracks
    %li
      %a.logout{ :href => '/logout' } log out
    %li
      %a{ :href => import_items_path } import

app/views/items/new.html.haml
%h1 New item

= render 'form'

= link_to 'Back', items_path

app/views/items/show.html.haml
- content_for :title, "#{@item.artist} - #{@item.title}"

.container-fluid#item_show
  %h1
    %a{ href: root_url(search: @item.artist) }= @item.artist
    \-
    %em= @item.title
  %h2
    #{@item.format} released in
    %a{ href: root_url(search: @item.year) }= @item.year
    on
    %a{ href: root_url(search: @item.label) }= @item.label
  %h3
    Added on #{@item.created_at.strftime('%A, %B %-d, %Y')}

  .row
    - if @release.image_url.present?
      .col-md-4.image.album-art
        %img.img-responsive{ src: @release.image_url }
        %br
    .col-md-7
      %p
        %b Condition:
        = @item.condition
      %p
        %b Color:
        = @item.color
      %p
        %b Price paid:
        = @item.price_paid
      %p
        %b Genre:
        = @item.genres.to_a.join(', ')
      %p
        %b Style:
        = @item.styles.to_a.join(', ')
      - if @item.tracks.exists?
        .tracklist
          %b Tracklist
          %ul
            - @item.tracks.order(:number).each do |track|
              %li
                %strong= track.number
                - if track.artist != @item.artist
                  #{track.artist} -
                = track.name
                - if track.duration.present?
                  (#{track.duration})
      - elsif @release.extra_info?
        - if @release.tracklist
          .tracklist
            %b Tracklist
            %ul
              - @release.tracklist.each do |track|
                %li #{track.position}: #{track.title}
      - if @release.notes.present?
        %p
          %b Notes:
          %br
          - @release.notes.to_s.lines.each do |line|
            = line.html_safe
            %br

      .last-cleaned
        %b Last cleaned:
        - if @item.last_cleaned_at.present?
          = @item.last_cleaned_at.strftime("%B %-d, %Y")
        - else
          Never
        = button_to("Mark as cleaned", mark_as_cleaned_item_path(@item), class: "btn btn-light", form: {style: 'display:inline-block;'}) 

      - if @item.embedding.present?
        .similar-items
          %b Similar Items
          %ul
            - @item.similar_items.each do |item|
              %li
                %a{ href: item_path(item) }
                  #{item.artist} - #{item.title}

      %p
        - if @item.discogs_url.present?
          = button_to("Discogs Link", @item.discogs_url, method: :get, class: "btn btn-light", form: {style: 'display:inline-block;'})
        = button_to("Edit", edit_item_path(@item), method: :get, class: "btn btn-light", form: {style: 'display:inline-block;'})

- content_for :nav do
  %ul.nav.navbar-nav
    %li
      %a{ :href => '/stats' } stats
    %li
      %a{ :href => random_items_path } random
    %li
      %a{ href: discover_items_path } discover
    %li
      %a.logout{ :href => '/logout' } log out

app/views/items/stats.html.haml
- content_for :title, "Stats"

.content#stats
  %h1 Stats for #{Item.count} items:

  .switcher
    %a.active{ :href => 'javascript:', 'data-target' => '.graphs' } Graphs
    |
    %a{ :href => 'javascript:', 'data-target' => '.texts' } Words
    |
    %a{ :href => '/items/time_machine' } Time Machine

  .graphs
    %h2 Year
    = column_chart Item.stats_for_field(:year), :library => google_column_charts_options

    %h2 Format
    = pie_chart Item.stats_for_field(:format), :height => '600px', :library => google_pie_charts_options

    %h2 Condition
    = pie_chart Item.stats_for_field(:condition), :height => '600px', :library => google_pie_charts_options

    %h2 Price Paid
    %p
      %em Prices paid fewer than 5 times are excluded
    = column_chart Item.price_stats.select { |k,v| v >= 5 }, :library => google_column_charts_options

    %h2 Month added
    = column_chart items_per_month, :library => google_column_charts_options

    %h2 Day of week added
    = column_chart items_per_day_of_week, :library => google_column_charts_options

    %h2 Size over time
    = line_chart Item.growth_by_week, :library => google_column_charts_options

    %h2 Items added per day
    #cal-heatmap

  .texts.none
    - [:artist, :label, :color].each do |field|
      .column
        %h2 Top 10 #{field.to_s.titleize.pluralize}
        = top_10(field)
    %div{ :style => 'clear:both;' }

    - ['title', 'artist', 'label', 'year'].each do |field|
      %h2 #{field.titleize} Frequency
      .frequency{ 'data-field' => field }

    %h2 Price Stats
    %h3 Minimum: #{sprintf("$%0.02f", @prices[:min_price])}
    %h3 Maximum: #{sprintf("$%0.02f",@prices[:max_price])}
    %h3 Average: #{sprintf("$%0.02f", @prices[:avg_price])}
    %h3 Median: #{sprintf("$%0.02f", @prices[:median_price])}